# Fix this crap!

# Offense count: 6
Metrics/AbcSize:
  Max: 40

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 200

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30
